# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/misaka10987"
params.icon = "brand-github"

[[social]]
identifier = "qq"
name = "QQ"
url = "http://2208129531.qzone.qq.com"
params.icon = "brand-qq"

[[social]]
identifier = "wechat"
name = "WeChat"
url = "/wechat.jpg"
params.icon = "brand-wechat"

[[social]]
identifier = "reddit"
name = "Reddit"
url = "https://www.reddit.com/user/misaka10987/"
params.icon = "brand-reddit"

[[social]]
identifier = "email"
name = "EMail"
url = "mailto:misaka10987@outlook.com"
params.icon = "mail"

[[social]]
identifier = "lichess"
name = "lichess.org"
url = "https://lichess.org/@/misaka10987"
params.icon = "chess-knight"

[[social]]
identifier = "zhihu"
name = "知乎"
url = "https://www.zhihu.com/people/misaka10987"
params.icon = "brand-zhihu"
